### ISSUE TITLE
Issue: Incorrect Handling of Mutable Default Arguments in Functions

### ISSUE THREAD

**Issue by iz-Manik** [mevipinmaurya/hbtuHacktoberfest2024#4]
About the Issue:
In Python, using mutable objects (such as lists or dictionaries) as default arguments in function definitions can lead to unexpected behavior. When the function is called multiple times without specifying the argument, the same object is reused across calls, causing values from previous calls to persist.

Goal:
The goal is to understand and fix the issue of mutable default arguments by using a more appropriate method (such as initializing the default to None and creating a new object inside the function). This prevents unexpected behavior and ensures correct functionality when using default arguments.

Technology Stack:
Python
Built-in Functions
Mutable Data Types: Lists, Dictionaries
None Keyword

Features/Outcomes:
The function will work correctly and initialize new lists or dictionaries each time it is called without the argument.
Users will no longer experience issues with persistent values across multiple calls to the function when no explicit argument is provided.

**Comment by mevipinmaurya** [comment]
Done
